[versions]
agp = "8.2.2"
kotlin = "2.0.0"
droidCompileSdk = "35"
droidTargetSdk = "35"
droidMinSdk = "16"
lifecycleProcess = "2.8.7"
swiftKlib =  "0.6.3"
compose-multiplatform = "1.7.0"

[libraries]
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
swiftklib = { id = "io.github.ttypic.swiftklib", version.ref = "swiftKlib" }


composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }